### ISSUE TITLE
TypeDef is not defined

### ISSUE THREAD

**Issue by Pamnig** [miso-xyz/UniShield#4]
Failed to save cleaned ASM!
   └ 'TypeDef BlackBerry.Enums.BotResult (02000045) is not defined in this module (BlackBerry.dll). A type was removed that is still referenced by this module.'
   
https://cdn.discordapp.com/attachments/1064730387957424219/1117791821377060914/image.png

**Comment by miso-xyz** [comment]
Can you send me your sample? Thanks

**Comment by Pamnig** [comment]
https://anonfiles.com/l63cj3ycz2/BlackBerry_dll

**Comment by Pamnig** [comment]
missclick 💀

**Comment by miso-xyz** [comment]
Ok so, I've just realised that there are two completely different obfuscators named "NetShield"

The one im targetting is in the readme.
The one people uses (which is actually decent) is a different obfuscator.

I've also updated the readme, specifying that UniShield does not support the decent NetShield

Sorry about the confusion, thank you.
